name: Optimize Thumbnails

on:
  push:
    paths:
      - 'thumbs/**.raw'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # This is good, it waits for the last upload

permissions:
  contents: write

jobs:
  optimize:
    runs-on: ubuntu-latest
    # This prevents the bot from triggering its own loop
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Settle Delay
        run: sleep 30 # Wait 30 seconds for Apps Script to finish the rest of the batch
